import type { CodegenConfig } from "@graphql-codegen/cli";

// schema/aem.graphql is fetched from the local AEM instance's generated
// GraphQL schema (regenerated by AEM automatically whenever a Content
// Fragment Model changes) via `npm run fetch-schema` — not hand-maintained.
// It's a plain SDL text file (served as .GQLschema, not an introspectable
// POST endpoint), so codegen reads it as a local file rather than a URL.
const config: CodegenConfig = {
  schema: "schema/aem.graphql",
  documents: ["graphql/operations/*.graphql"],
  generates: {
    "lib/aem/generated.ts": {
      plugins: ["typescript", "typescript-operations"],
      config: {
        // AEM's persisted-query GET endpoint (matrix params) doesn't use
        // GraphQL variables the way a POST client would, but the generated
        // *Variables types are still useful for documenting each query's
        // required params.
        skipTypename: true,
      },
    },
  },
};

export default config;
