import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const editorEnabled = process.env.NEXT_PUBLIC_AEM_EDITOR_ENABLED === "true";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      {editorEnabled && (
        <>
          {/* No SRI: Adobe's live UE service script, not a versioned CDN asset; dev-only via editorEnabled */}
          <script src="https://universal-editor-service.adobe.io/cors.js" async />
          {/*
            "aem65:" not "aem:" — classic on-prem AEM 6.5 uses a distinct
            connection scheme from AEM as a Cloud Service; using the wrong
            one can leave basic field editing working (tolerant fallback)
            while the newer "add new component" flow silently never
            registers. Verify both still work after this change.
          */}
          <meta
            name="urn:adobe:aue:system:aemconnection"
            content={`aem65:${process.env.NEXT_PUBLIC_AEM_EDITOR_CONNECTION_URL}`}
          />
          <meta
            name="urn:adobe:aue:config:service"
            content={process.env.NEXT_PUBLIC_UE_CONFIG_SERVICE_URL}
          />
          {/*
            Lets authors create a brand-new Content Fragment directly from
            the "+" button on a page-sections/section-group-items container
            in the Universal Editor canvas, instead of having to pre-create
            it in the classic Assets console first. See public/static/*.json
            for the actual filter/cf-creation definitions. No component-models.json:
            our components are pure Content-Fragment-backed (plugins.aem65.cf +
            data-aue-resource identifying which fragment/model to introspect),
            so Universal Editor derives the properties-rail field list from the
            underlying CFM itself rather than a separately hand-maintained field
            list — confirmed via FluffyJaws.
            `async` here: not for the browser (this `type` isn't a JavaScript
            MIME type, so per the HTML script-processing spec it never
            fetches/executes these regardless of async/defer — they're inert
            data markers Universal Editor's own JS reads manually), but React
            itself requires async on any <script> it auto-hoists into <head>
            or it can't guarantee execution order and throws a hydration
            error ("Cannot render a sync or defer <script> ... without
            knowing its order") — confirmed by removing it and seeing exactly
            that error.
          */}
          <script
            async
            type="application/vnd.adobe.aue.component+json"
            src="/static/component-definition.json"
          />
          <script
            async
            type="application/vnd.adobe.aue.filter+json"
            src="/static/component-filters.json"
          />
        </>
      )}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
